name: "build-on-push"
on: [push]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04] #, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev at-spi2-core xvfb

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - run: node .github/get_target.js

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the app
        run: pnpm tauri build

      # - name: Build the app
      #   uses: tauri-apps/tauri-action@v0

      - name: List files
        run: ls src-tauri/target/release

      - name: Test
        if: matrix.platform != 'ubuntu-20.04'
        run: pnpm test

      - name: Test
        if: matrix.platform == 'ubuntu-20.04'
        run: xvfb-run pnpm test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: image-tmp
          path: test/tmp/*

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: image-diff
          path: test/diff/*

      - name: Set env variables
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "RUST_TARGET=$(node .github/get_target.js)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: "bins/${{ env.RUST_TARGET }}"
          path: "src-tauri/target/release/${PACKAGE_NAME}*"
          if-no-files-found: error

      # - name: Set env variables
      #   run: |
      #     echo "BIN_NAME=${PACKAGE_NAME}-${PACKAGE_VERSION}-${SHA_SHORT}-${RUST_TARGET}" >> $GITHUB_ENV

      # - name: Pack executable
      #   run: |
      #     mkdir -p bins/${BIN_NAME}
      #     cp src-tauri/target/release/${PACKAGE_NAME}* bins/${BIN_NAME}
      #     tar -C bins -czvf ${BIN_NAME}.tar.gz ${BIN_NAME}

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: "${{ env.BIN_NAME }}"
      #     path: "${{ env.BIN_NAME }}.tar.gz"
      #     if-no-files-found: error
